stages:
  - test

variables:
  DEBIAN_FRONTEND: noninteractive

test:
  stage: test
  image: ubuntu:20.04
  script:
    - apt update
    - apt install -y --no-install-recommends fakeroot xz-utils python3 python3-gpg e2fsprogs android-sdk-libsparse-utils abootimg tox python3-nose2 python3-mock python3-coverage pep8 pyflakes3 cpio python3-six
    - mkdir tools/keys
    - tools/generate-keys
    - tox
    - python3-coverage xml --rcfile=coverage-py38.ini -o coverage-py38.xml
  artifacts:
    reports:
      cobertura: coverage-py38.xml
