#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright (C) 2013 Canonical Ltd.
# Author: Stéphane Graber <stgraber@ubuntu.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import shutil

import sys
sys.path.insert(0, 'lib')

from systemimage import gpg

target_dir = "tests/keys/"
if not os.path.exists(target_dir):
    raise Exception("Missing tests/keys directory")

keys = (("master", "[TESTING] Ubuntu Archive Master Signing Key",
                   "ftpmaster@ubuntu.com", 0),
        ("system", "[TESTING] Ubuntu System Image Master Signing Key",
                   "system-image@ubuntu.com", 0),
        ("signing", "[TESTING] Ubuntu System Image Signing Key (YYYY)",
                    "system-image@ubuntu.com", "2y"),
        ("device", "[TESTING] Random OEM Signing Key (YYYY)",
                   "system-image@ubuntu.com", "2y"))

for key_name, key_description, key_email, key_expiry in keys:
    key_dir = "%s/%s/" % (target_dir, key_name)
    if os.path.exists(key_dir):
        shutil.rmtree(key_dir)
    os.makedirs(key_dir)

    uid = gpg.generate_signing_key(key_dir, key_description, key_email,
                                   key_expiry)

    print("%s <%s>" % (uid.name, uid.email))

# All done, let's mark it as done
open("tests/keys/generated", "w+").close()
