#!/usr/bin/python3
# Dependencies:
#  - python2 (>= 2.7): python-gpgme, python-coverage
#  - python3 (>= 3.2): python3-gpgme

import glob
import os
import re
import shutil
import sys
import unittest

coverage = True
try:
    from coverage import coverage
    cov = coverage()
    cov.start()
except ImportError:
    print("No coverage report, make sure python-coverage is installed")
    coverage = False

sys.path.insert(0, 'lib')

if len(sys.argv) > 1:
    test_filter = sys.argv[1]
else:
    test_filter = ''

tests = [t[:-3] for t in os.listdir('tests')
         if t.startswith('test_') and t.endswith('.py') and
         re.search(test_filter, t)]
tests.sort()
suite = unittest.TestLoader().loadTestsFromNames(tests)
res = unittest.TextTestRunner(verbosity=2).run(suite)

if coverage:
    if os.path.exists('tests/coverage'):
        shutil.rmtree('tests/coverage')
    cov.stop()
    cov.html_report(include=glob.glob("lib/systemimage/*.py"),
                    directory='tests/coverage')
